version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        networks:
            - app-network

    db:
        image: postgres:14.1
        environment:
            POSTGRES_DB: product_catalog
            POSTGRES_USER: user_db
            POSTGRES_PASSWORD: 123
        ports:
            - "5432:5432"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
